from __future__ import annotations

from typing import Protocol

from pr_listener.models import OutboxEvent, PRRecord, RunRecord


class RunRepository(Protocol):
    async def upsert_pr(self, pr: PRRecord) -> PRRecord: ...
    async def get_pr_by_repo_number_sha(self, repo: str, pr_number: int, head_sha: str) -> PRRecord | None: ...
    async def create_run(self, run: RunRecord) -> RunRecord: ...
    async def get_run_by_key(self, run_key: str) -> RunRecord | None: ...
    async def append_outbox(self, event: OutboxEvent) -> OutboxEvent: ...
    async def mark_outbox_published(self, event_id: str) -> None: ...
    async def get_unpublished_outbox(self, limit: int = 100) -> list[OutboxEvent]: ...
    async def delivery_seen(self, delivery_id: str) -> bool: ...
    async def record_delivery(self, delivery_id: str) -> None: ...
